# create_models/basic_plane.py

def create_obj_plane(filename="basic_plane.obj"):
    """
    Generates a simple .obj file for a basic airplane model.
    The model consists of a main fuselage and a set of wings.
    
    Args:
        filename (str): The name of the output .obj file.
    """
    
    # Vertices for a simple plane shape
    vertices = [
        # Fuselage
        (0.0, 0.0, 5.0),    # v0 - Nose
        (-1.0, 0.5, -5.0),  # v1 - Left rear top
        (-1.0, -0.5, -5.0), # v2 - Left rear bottom
        (1.0, 0.5, -5.0),   # v3 - Right rear top
        (1.0, -0.5, -5.0),  # v4 - Right rear bottom
        
        # Left Wing
        (-1.0, 0.0, 0.0),   # v5 - Left wing root
        (-5.0, 0.0, -1.0),  # v6 - Left wing tip
        (-1.0, 0.0, -4.0),  # v7 - Left wing rear
        
        # Right Wing
        (1.0, 0.0, 0.0),    # v8 - Right wing root
        (5.0, 0.0, -1.0),   # v9 - Right wing tip
        (1.0, 0.0, -4.0),   # v10 - Right wing rear

        # Vertical Stabilizer (tail fin)
        (0.0, 0.5, -4.0),   # v11 - Tail top
        (0.0, 0.0, -5.0)    # v12 - Tail bottom
    ]

    # Faces connecting the vertices
    faces = [
        # Fuselage (Side faces)
        (1, 0, 3), # Right side
        (3, 0, 4),
        (2, 0, 1), # Left side
        (4, 0, 2),
        (1, 3, 4), # Rear face
        (1, 4, 2),
        
        # Left Wing (top and bottom)
        (5, 6, 7), # Left wing (top)
        
        # Right Wing (top and bottom)
        (8, 9, 10), # Right wing (top)
        
        # Vertical Stabilizer (tail fin)
        (11, 12, 3),
        (11, 4, 12)
    ]

    with open(filename, "w") as f:
        f.write("# Simple Plane Model\n")
        f.write("# Generated by create_models/basic_plane.py\n\n")
        
        # Write vertices to the file
        for v in vertices:
            f.write(f"v {v[0]} {v[1]} {v[2]}\n")
            
        f.write("\n")
        
        # Write faces to the file (adjusting for 1-based indexing)
        for face in faces:
            f.write(f"f {face[0]+1} {face[1]+1} {face[2]+1}\n")

    print(f"Successfully generated {filename} with a basic plane model.")

# This part runs the function when the script is executed directly
if __name__ == "__main__":
    create_obj_plane()
